[pi_sensors]
raspberrypi-0w1 ansible_host=192.168.1.101 location=office
raspberrypi-0w2 ansible_host=192.168.1.102 location=bedroom  
raspberrypi-0w3 ansible_host=192.168.1.103 location=plant
raspberrypi-0w4 ansible_host=192.168.1.104 location=dining

[pi_sensors:vars]
ansible_user=pi
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
